site_name: PSA GBO/DvTP

theme:
  name: material
  language: nl
  features:
    - navigation.sections
    - content.code.copy
    - content.code.annotate

markdown_extensions:

  # Mermaid diagrammen
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Includes voor diagrammen
  - pymdownx.snippets:
      base_path:
        - docs
      check_paths: true

  # Automatische inhoudsopgave
  - toc:
      permalink: true
      toc_depth: 3

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid-init.js

plugins:
  - search

  # PDF generatie
  - with-pdf:
      cover_title: "GBO / DvTP"
      cover_subtitle: "Project Start Architectuur"
      cover_logo: media/ictu-logo.png
      output_path: pdf/PSA-GBO-DvTP.pdf
      ordered_chapter_level: 1
      enabled_if_env: ENABLE_PDF_EXPORT
      # BELANGRIJK voor Material theme
      render_js: true
      two_columns_level: 0
      toc_level: 2
      css: stylesheets/pdf.css
      content_selector: ".md-content__inner"

nav:
  - Home: index.md

  - PSA:
    - Inleiding: psa/inleiding.md
    - Context: psa/context.md
    - Ecosysteem en rollen: psa/ecosysteem.md
    - Use Cases: psa/use-cases.md
    - Interactiepatronen: psa/interactiepatronen.md
    - Architectuurprincipes: psa/architectuurprincipes.md
    - Logische architectuur: psa/generieke-functies.md
    - Capabilities: psa/capabilities.md
    - Architectuurkaders: psa/architectuurkaders.md
    - Realisatiestrategie: psa/realisatiestrategie.md
    - Open Vraagstukken: psa/open-vraagstukken.md

  - Use Cases:
    - Zorgeloos Vastgoed: use-cases/zorgeloos-vastgoed.md
    - Gebruik vastgoedgegevens: use-cases/lvg.md
