site_name: PSA GBO/DvTP
theme:
  name: material
  language: nl
  features:
    - navigation.sections
    - content.code.copy

markdown_extensions:
# 1. Hiermee herkent MkDocs de ```mermaid blokken
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# 2. Hiermee kun je externe bestanden (zoals je .mmd files) invoegen
  - pymdownx.snippets:
      base_path: docs
      check_paths: true

plugins:
  - search

nav:
  - Home: index.md
  - PSA:
    - Inleiding: psa/inleiding.md
    - Context: psa/context.md
    - Ecosysteem en rollen: psa/ecosysteem.md
    - Use Cases: psa/use-cases.md
    - Interactiepatronen: psa/interactiepatronen.md
    - Architectuurprincipes: psa/architectuurprincipes.md
    - Logische architectuur: psa/generieke-functies.md
    - Capabilities: psa/capabilities.md
    - Architectuurkaders: psa/architectuurkaders.md
    - Realisatiestrategie: psa/realisatiestrategie.md
    - Open Vraagstukken: psa/open-vraagstukken.md
  - Use Cases:
    - Zorgeloos Vastgoed: use-cases/zorgeloos-vastgoed.md
    - Gebruik vastgoedgegevens: use-cases/lvg.md
